/**
 * Seed the database with sample data, removing all existing data.
 */

import bcrypt from "bcryptjs";
import { atms, ledger, users, transactions } from "./schema.js";
import * as schema from "./schema.js";
import { CASH_VAULT_USER_ID, SHAREHOLDER_EQUITY_USER_ID } from "./constants.js";
import { reset } from "drizzle-seed";
import { sql, getTableName } from "drizzle-orm";
import { drizzle } from "drizzle-orm/neon-http";
import env from "../env.js";

// Initialize db here instead of importing from db/index.ts because db/index.ts
// uses neon-serverless (needed for interactive database transactions), but
// drizzle-seed only supports neon-http.
const db = drizzle(env.DATABASE_URL);

await reset(db, schema);

// Create internal accounts
await db.insert(users).values([
  {
    userId: CASH_VAULT_USER_ID,
    fullName: "Cash Vault",
    phoneNumber: "+6500000000",
    email: "cash-vault@internal.bombastic-banking",
    hashedPin: await bcrypt.hash("internal", 10),
    isInternal: true,
  },
  {
    userId: SHAREHOLDER_EQUITY_USER_ID,
    fullName: "Shareholder Equity",
    phoneNumber: "+6500000001",
    email: "shareholder-equity@internal.bombastic-banking",
    hashedPin: await bcrypt.hash("internal", 10),
    isInternal: true,
  },
]);

// Since userId is "generated by default as identity", the userId sequence
// needs to be updated to account for the manually-set internal account userIds
await db
  .select({
    _: sql`setval(pg_get_serial_sequence(${getTableName(users)}, ${users.userId.name}), max(${users.userId}))`,
  })
  .from(users);

// Initial transaction for bank capitalization
const [{ transactionId }] = await db
  .insert(transactions)
  .values({
    type: "internal",
    description: "Initial bank capitalization",
  })
  .returning();

// Create ledger entries
await db.insert(ledger).values([
  {
    transactionId,
    userId: CASH_VAULT_USER_ID,
    change: "10000.00", // Asset increase (positive)
  },
  {
    transactionId,
    userId: SHAREHOLDER_EQUITY_USER_ID,
    change: "-10000.00", // Liability increase (negative)
  },
]);

// Create ATM
await db.insert(atms).values({ location: "OCBC Centre Branch" });
